services:
  webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - doctor_pill_network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - doctor_pill_network
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

networks:
  doctor_pill_network:
    driver: bridge

volumes:
  nginx_data:
  nginx_letsencrypt:
